### PR TITLE
Add helper text for experimental variable input

### PR DESCRIPTION
**Pull request by KochTobi**
Solves #738 
image

### CODE REVIEW

**Comment by Shraddha0903** [comment]
@KochTobi The helper text looks good although can we adjust the text to 3 lines only? 
I cannot see the placeholder text in this screenshot. We provide placeholder text for examples of the values and how they should be written. Font colour for placeholder text is lighter than body text (Secondary text)
Each time the user adds an extra variable in the dialog, it should show the same example as placeholder text in the text fields.

**Review by Shraddha0903 — CHANGES_REQUESTED** [review]
@KochTobi The helper text looks good although can we adjust the text to 3 lines only? 
I cannot see the placeholder text in this screenshot. We provide placeholder text for examples of the values and how they should be written. Font colour for placeholder text is lighter than body text (Secondary text)
Each time the user adds an extra variable in the dialog, it should show the same example as placeholder text in the text fields.

**Comment by KochTobi** [comment]
> @KochTobi The helper text looks good although can we adjust the text to 3 lines only?

It is quite some effort to do this and increases complexity. To do this the input field would need to be wider which in turn makes the dialog wider.

> I cannot see the placeholder text in this screenshot. We provide placeholder text for examples of the values and how they should be written. Font colour for placeholder text is lighter than body text (Secondary text) Each time the user adds an extra variable in the dialog, it should show the same example as placeholder text in the text fields.

I did not notice them in the draft. They are added now.

**Review by Shraddha0903 — CHANGES_REQUESTED** [review]
@KochTobi Awesome!
It's just that it takes up a lot of space for a single property, was trying to reduce that.

Just one other thing the blue cross at the end of the variable row is not aligned with the text fields, seems to be a little down (maybe coz its blue? 😛) Can we align it with the fields? 

Screenshot 2024-08-22 at 15 08 32

**Comment by KochTobi** [comment]
> @KochTobi Awesome! It's just that it takes up a lot of space for a single property, was trying to reduce that.
> 
> Just one other thing the blue cross at the end of the variable row is not aligned with the text fields, seems to be a little down (maybe coz its blue? 😛) Can we align it with the fields?

Not easy no :/ The image is perfectly aligned. There is some transparent background inside the icon but changing that would be a lot of effort / I don't know how to easily do that with shipped icons.

> 
> Screenshot 2024-08-22 at 15 08 32

**Comment by KochTobi** [comment]
> > @KochTobi Awesome! It's just that it takes up a lot of space for a single property, was trying to reduce that.
> > Just one other thing the blue cross at the end of the variable row is not aligned with the text fields, seems to be a little down (maybe coz its blue? 😛) Can we align it with the fields?
> 
> Not easy no :/ The image is perfectly aligned. There is some transparent background inside the icon but changing that would be a lot of effort / I don't know how to easily do that with shipped icons.
> 
> > Screenshot 2024-08-22 at 15 08 32

Ah wait. I understand what you mean. Let me check

**Review by Shraddha0903 — COMMENTED** [review]
@KochTobi I feel we can wait for @Steffengreiner to have a look if it's possible, i.e. to top align the icon with respect to the text box only. If it's not possible or takes a lot of effort then we can move to another solution (for e.g. displaying the option to delete the row on the bottom of each row)

**Review by Shraddha0903 — COMMENTED** [review]
@KochTobi Nicee job! I think it looks good now. 👍

**Pull request merged**
