### PR TITLE
Enhance XLSX templates with examples for expected properties #675

### PR DESCRIPTION
**Pull request by KochTobi**
Adds a description to cells (called prompt box in excel terms) to help users to fill out the excel sheets.
Adds some linking to certain column headers to forward to urls.
Registration templates are now generated on the fly leading to the following files:

[ngs_measurement_registration_sheet.xlsx](https://github.com/user-attachments/files/17503713/ngs_measurement_registration_sheet.xlsx)
[proteomics_measurement_registration_sheet.xlsx](https://github.com/user-attachments/files/17503714/proteomics_measurement_registration_sheet.xlsx)
[QVAMP_ngs_measurements.xlsx](https://github.com/user-attachments/files/17503715/QVAMP_ngs_measurements.xlsx)
[QVAMP_proteomics_measurements.xlsx](https://github.com/user-attachments/files/17503716/QVAMP_proteomics_measurements.xlsx)

### CODE REVIEW

**Review by Shraddha0903 — CHANGES_REQUESTED** [review]
Hi @KochTobi, good job! 🤩 I have some points regarding 2-3 columns,

In **Proteomics**, there are missing examples for the columns - Technical Replicate, Digestion Enzyme, Enrichment method, Labelling type, Label. I will ask Francesca for them and update you.

In **Genomics**, the description for sample pool groups is not the same as the one in the Proteomics sheet. The current one is a little confusing, can you make it the same as Proteomics?

For both **Genomics and Proteomics**,
Can we add a Tip at the end of the description for all the cells in the columns (for Organisation ID and Instrument/MS Device), that tells the user to click on the header to get the property values. The highlighted header and its tooltip are good indicators, but users could overlook it so a double check would be better.

For Organisation ID:
A unique identifier of the organisation where the measurement has been conducted.
Tip: You can click on the column header (Organisation ID) to go to the ROR website, search for your organisation and get the Organisation URL.

For Instrument/MS Device:
The instrument that has been used for the measurement. To avoid ambiguities, we expect an ontology term CURIE (e.g. NCIT:C12434)
Tip: You can click on the column header (Instrument) to go to the Data Manager where you can use our Ontology Search to query the CURIE for your Instrument.

And one last question - Did we plan to remove the Property Information sheet from the excel templates? I did not see one

**Comment by sven1103** [comment]
Hi @KochTobi and @Shraddha0903 , 

great improvement, i would like if you can also contact Daniel what he thinks. 

**Points that I observed during my journey**

- I am missing explanations in the sample metadata sheet
- The process to download the sample registration sheet and measurement registration sheet is different, can this be harmonized (not scope of this PR, but I would like this to be tracked then in a separate issue please)
- Link for ROR and Ontology, the browser opening out of Excel hit me by surprise, but maybe that is sth users will figure out quickly 
- You only get the tooltips when you hover the empty cells, and this will also happen when you have entered values. Why not having the tooltip in the header? This is where at least I looked for it and was sad, that nothing happens. I am worried, that the tooltips for every cell are becoming quickly annoying, especially if you are working in the cells. 

That is just my raw direct feeling about it, I know that you but a lot of heart in it! So take it please just as feedback 🫶 

Best, Sven

**Comment by KochTobi** [comment]
> Hi @KochTobi, good job! 🤩 I have some points regarding 2-3 columns,
> 
> In **Proteomics**, there are missing examples for the columns - Technical Replicate, Digestion Enzyme, Enrichment method, Labelling type, Label. I will ask Francesca for them and update you.

Hi Shraddha, I am only observing missing descriptions for technical replicate in the proteomics registration sheet.
In the proteomics edit sheet I am missing 

- measurement id
- technical replicate
- organisation name
- ms device name

In the ngs registration sheet all columns have a description but for the ngs edit sheet I am missing

- measurement id
- organisation name
- instrument name

It would be great to have some input here.

> 
> In **Genomics**, the description for sample pool groups is not the same as the one in the Proteomics sheet. The current one is a little confusing, can you make it the same as Proteomics?

Done.
> 
> For both **Genomics and Proteomics**, Can we add a Tip at the end of the description for all the cells in the columns (for Organisation ID and Instrument/MS Device), that tells the user to click on the header to get the property values. The highlighted header and its tooltip are good indicators, but users could overlook it so a double check would be better.
> 
> For Organisation ID: A unique identifier of the organisation where the measurement has been conducted. Tip: You can click on the column header (Organisation ID) to go to the ROR website, search for your organisation and get the Organisation URL.
> 
> For Instrument/MS Device: The instrument that has been used for the measurement. To avoid ambiguities, we expect an ontology term CURIE (e.g. NCIT:C12434) Tip: You can click on the column header (Instrument) to go to the Data Manager where you can use our Ontology Search to query the CURIE for your Instrument.

I cannot add multiple lines. So it would all be in one text. I can add Tip: before it but I do not know if this is what you want.
> 
> And one last question - Did we plan to remove the Property Information sheet from the excel templates? I did not see one

I understood it this way? Do you want to keep it? If so I guess the descriptions should be the same.

**Comment by Shraddha0903** [comment]
> Hi Shraddha, I am only observing missing descriptions for technical replicate in the proteomics registration sheet. In the proteomics edit sheet I am missing
> 
> * measurement id
> * technical replicate
> * organisation name
> * ms device name
> 
> In the ngs registration sheet all columns have a description but for the ngs edit sheet I am missing
> 
> * measurement id
> * organisation name
> * instrument name
> 
> It would be great to have some input here.

Okay, thanks for letting me know. I will provide you with all those definitions and examples.

> I understood it this way? Do you want to keep it? If so I guess the descriptions should be the same.

Yes, I think we should keep. We can add more details over there. Yes we keep the same descriptions.

**Comment by Shraddha0903** [comment]
Thank you @sven1103 for your nice observations! 🙂

> * I am missing explanations in the sample metadata sheet

Yess, that was the next thing planned after the measurements.

> * The process to download the sample registration sheet and measurement registration sheet is different, can this be harmonized (not scope of this PR, but I would like this to be tracked then in a separate issue please)

Yess, I agree they need to be harmonized. I had planned of removing the Templates component altogether, the issue was not created though. I saw that you have created one, thanks, we can do that. 

> * Link for ROR and Ontology, the browser opening out of Excel hit me by surprise, but maybe that is sth users will figure out quickly

I hope the tip will help!

> * You only get the tooltips when you hover the empty cells, and this will also happen when you have entered values. Why not having the tooltip in the header? This is where at least I looked for it and was sad, that nothing happens. I am worried, that the tooltips for every cell are becoming quickly annoying, especially if you are working in the cells.

As Tobi said, we are not sure if the user will click on the header to see the tooltip as it has no tooltip icon to indicate that. I feel keeping the tooltips for the header and the first cell would be a good idea as the user starts from the first cell and would not miss that. But I also agree with @KochTobi  we should wait for some feedback from the users about the same.

> That is just my raw direct feeling about it, I know that you but a lot of heart in it! So take it please just as feedback 🫶

Always good to have such good feedback!

**Review by Shraddha0903 — CHANGES_REQUESTED** [review]
Thanks for adding the property sheets, @KochTobi ! Few points:

1. Add description for Measurement ID (just saw that it’s not present, promise this is the last one :P)

```
   QBiC Measurement ID:
   Title: QBiC Measurement ID
   Input message: A unique identifier of the measurement that will be linked to each sample.
```

2. The properties index i5 and index i7 are actually mandatory but are not marked as mandatory in the metadata sheet and the property sheet as well.
Note: You get an error after validation in the Registration step, in validation no error. This had come up in the Workshop)

3. Formatting for the Metadata sheet:

    Font: Open Sans, size 12

4. Formatting for the Property sheets:

    a. Font: Open Sans, size 12 (this is what was used before. Better for readability)
    b. Borders for the columns
    c. Wrap text for the cells with long descriptions (Organisation URL and Instrument, specifically)

**Review by Shraddha0903 — APPROVED** [review]
Thanks for making the changes, @KochTobi! 🙂
The font looks good!

**Review by Shraddha0903 — APPROVED** [review]
@KochTobi Looks all good to me now! 👍

**Pull request merged**
