### PR TITLE
Increase ontology column length

### PR DESCRIPTION
**Pull request by KochTobi**

### CODE REVIEW

**Comment by wow-such-code** [comment]
converting to draft to make other similar changes, e.g.
alter table sample modify species text;
alter table sample modify specimen text;
alter table sample modify analyte text;

**Comment by KochTobi** [comment]
@wow-such-code what was the plan here? The length in the jpa annotation helps hibernate determine the length in the column.

**Comment by wow-such-code** [comment]
> @wow-such-code what was the plan here? The length in the jpa annotation helps hibernate determine the length in the column.

been a whilte, but afaik these are json columns and when the two of us worked on fixing this on the server we changed them to text so we could guarantee long ontology entries to work.

**Comment by KochTobi** [comment]
solved by https://github.com/qbicsoftware/data-manager-app/pull/605

**Pull request closed without merging**
